### ISSUE TITLE
/profile

### ISSUE THREAD

**Issue by Mattaus-Isenberg** [Mattaus-Isenberg/WhiteBoardMaster#36]
Profile for registered user, includes all boards created by user for future use, data is stored as values to reconstruct the whiteboard on demand.

**Comment by micahThor** [comment]
Created /profile route in ApplicationUserController class to handle display of profile data.  An instance of ApplicationUser for logged in user is passed back to front-end

**Comment by micahThor** [comment]
all requirements met!
